# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WhoLetTheDogsOut' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'IQKeyboardManager'
  pod 'PromisesSwift', '~> 1.2.4'
  pod 'Alamofire', '~> 4.7'
  pod 'AlamofireImage'
  pod 'ReachabilitySwift'

  target 'WhoLetTheDogsOutTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WhoLetTheDogsOutUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
